var types = preload("res://Types.gd").types

const s := 2.0 # Strong 
const n := 1.0 # Neutral
const w := 0.5 # Weak

var matchups = {
	types.NONE: {
		types.NONE: 	n,
		types.FIRE: 	n,
		types.ICE: 		n,
		types.FLORA: 	n,
		types.EARTH: 	n,
		types.ELECTRIC: n,
		types.WATER: 	n,
		types.METAL: 	n,
		types.WIND: 	n,
		types.TEXTILE: 	n,
		types.POLYMER: 	n,
		types.LIGHT: 	n,
		types.DARK: 	n,
		types.MIND: 	n,
	},
	types.FIRE: {
		types.NONE: 	n,
		types.FIRE: 	s,
		types.ICE: 		s,
		types.FLORA: 	s,
		types.EARTH: 	w,
		types.ELECTRIC: n,
		types.WATER: 	w,
		types.METAL: 	w,
		types.WIND: 	w,
		types.TEXTILE: 	s,
		types.POLYMER: 	s,
		types.LIGHT: 	w,
		types.DARK: 	s,
		types.MIND: 	n,
	},
	types.ICE: {
		types.NONE: 	n,
		types.FIRE: 	w,
		types.ICE: 		s,
		types.FLORA: 	s,
		types.EARTH: 	s,
		types.ELECTRIC: n,
		types.WATER: 	s,
		types.METAL: 	n,
		types.WIND: 	n,
		types.TEXTILE: 	w,
		types.POLYMER: 	s,
		types.LIGHT: 	w,
		types.DARK: 	w,
		types.MIND: 	n,
	},
	types.FLORA: {
		types.NONE: 	n,
		types.FIRE: 	w,
		types.ICE: 		w,
		types.FLORA: 	s,
		types.EARTH: 	s,
		types.ELECTRIC: s,
		types.WATER: 	s,
		types.METAL: 	w,
		types.WIND: 	n,
		types.TEXTILE: 	n,
		types.POLYMER: 	n,
		types.LIGHT: 	s,
		types.DARK: 	w,
		types.MIND: 	n,
	},
	types.EARTH: {
		types.NONE: 	n,
		types.FIRE: 	s,
		types.ICE: 		w,
		types.FLORA: 	w,
		types.EARTH: 	s,
		types.ELECTRIC: s,
		types.WATER: 	w,
		types.METAL: 	s,
		types.WIND: 	w,
		types.TEXTILE: 	w,
		types.POLYMER: 	n,
		types.LIGHT: 	s,
		types.DARK: 	n,
		types.MIND: 	s,
	},
	types.ELECTRIC: {
		types.NONE: 	n,
		types.FIRE: 	n,
		types.ICE: 		n,
		types.FLORA: 	w,
		types.EARTH: 	w,
		types.ELECTRIC: s,
		types.WATER: 	s,
		types.METAL: 	s,
		types.WIND: 	s,
		types.TEXTILE: 	w,
		types.POLYMER: 	w,
		types.LIGHT: 	n,
		types.DARK: 	s,
		types.MIND: 	n,
	},
	types.WATER: {
		types.NONE: 	n,
		types.FIRE: 	s,
		types.ICE: 		w,
		types.FLORA: 	w,
		types.EARTH: 	s,
		types.ELECTRIC: w,
		types.WATER: 	s,
		types.METAL: 	s,
		types.WIND: 	s,
		types.TEXTILE: 	s,
		types.POLYMER: 	w,
		types.LIGHT: 	w,
		types.DARK: 	n,
		types.MIND: 	n,
	},
	types.METAL: {
		types.NONE: 	n,
		types.FIRE: 	s,
		types.ICE: 		n,
		types.FLORA: 	s,
		types.EARTH: 	w,
		types.ELECTRIC: w,
		types.WATER: 	w,
		types.METAL: 	s,
		types.WIND: 	s,
		types.TEXTILE: 	s,
		types.POLYMER: 	n,
		types.LIGHT: 	n,
		types.DARK: 	n,
		types.MIND: 	w,
	},
	types.WIND: {
		types.NONE: 	n,
		types.FIRE: 	s,
		types.ICE: 		n,
		types.FLORA: 	n,
		types.EARTH: 	s,
		types.ELECTRIC: w,
		types.WATER: 	w,
		types.METAL: 	w,
		types.WIND: 	s,
		types.TEXTILE: 	s,
		types.POLYMER: 	n,
		types.LIGHT: 	n,
		types.DARK: 	n,
		types.MIND: 	n,
	},
	types.TEXTILE: {
		types.NONE: 	n,
		types.FIRE: 	w,
		types.ICE: 		s,
		types.FLORA: 	n,
		types.EARTH: 	s,
		types.ELECTRIC: s,
		types.WATER: 	w,
		types.METAL: 	w,
		types.WIND: 	w,
		types.TEXTILE: 	s,
		types.POLYMER: 	n,
		types.LIGHT: 	s,
		types.DARK: 	n,
		types.MIND: 	n,
	},
	types.POLYMER: {
		types.NONE: 	n,
		types.FIRE: 	w,
		types.ICE: 		w,
		types.FLORA: 	n,
		types.EARTH: 	n,
		types.ELECTRIC: s,
		types.WATER: 	s,
		types.METAL: 	n,
		types.WIND: 	n,
		types.TEXTILE: 	n,
		types.POLYMER: 	s,
		types.LIGHT: 	n,
		types.DARK: 	n,
		types.MIND: 	n,
	},
	types.LIGHT: {
		types.NONE: 	n,
		types.FIRE: 	s,
		types.ICE: 		s,
		types.FLORA: 	w,
		types.EARTH: 	w,
		types.ELECTRIC: n,
		types.WATER: 	s,
		types.METAL: 	n,
		types.WIND: 	n,
		types.TEXTILE: 	w,
		types.POLYMER: 	n,
		types.LIGHT: 	s,
		types.DARK: 	s,
		types.MIND: 	w,
	},
	types.DARK: {
		types.NONE: 	n,
		types.FIRE: 	w,
		types.ICE: 		s,
		types.FLORA: 	s,
		types.EARTH: 	n,
		types.ELECTRIC: w,
		types.WATER: 	n,
		types.METAL: 	n,
		types.WIND: 	n,
		types.TEXTILE: 	n,
		types.POLYMER: 	n,
		types.LIGHT: 	w,
		types.DARK: 	s,
		types.MIND: 	s,
	},
	types.MIND: {
		types.NONE: 	n,
		types.FIRE: 	n,
		types.ICE: 		n,
		types.FLORA: 	n,
		types.EARTH: 	w,
		types.ELECTRIC: n,
		types.WATER: 	n,
		types.METAL: 	s,
		types.WIND: 	n,
		types.TEXTILE: 	n,
		types.POLYMER: 	n,
		types.LIGHT: 	s,
		types.DARK: 	w,
		types.MIND: 	s,
	},
}

func get_matchup(attacking_type: int, defending_type: int) -> float:
	return matchups[attacking_type][defending_type]
